fix tests for check-command and check-command --returns

diff --git a/test/check-command--returns b/test/check-command--returns
--- a/test/check-command--returns
+++ b/test/check-command--returns
@@ -43,10 +43,10 @@ function usage () {
   dry-assert-code 2
   dry-refute-output "stdout"
   dry-assert-output "stderr" || return
-  grep "$case" <<<"$stderr" && {
+  egrep "EUSAGE|usage|invalid" <<<"$stderr" &>/dev/null && {
     PASS "it gracefully fails when $case"
   } || {
-    FAIL --next "stderr tells nothing about $case"
+    FAIL --next "stderr tells nothing about usage error"
     dry-diagnose "stderr"
   }
 }
@@ -54,16 +54,33 @@ function usage () {
 function failure () {
   dry-assert-code 1
   dry-refute-output "stderr"
-  test $(wc -l <<<"$output") -eq 1 &&  {
+  test $(wc -l <<<"$stdout") -eq 1 &&  {
     PASS "outputs exactly ONE line on stdout when $case"
   } || {
-    FAIL --next "outputs more than ONE line on stdout when $case"
+    FAIL --next "should output exactly ONE line on stdout when $case"
     dry-diagnose "stdout"
   }
-  grep -q -E "^FAIL .+" <<<"$output" >/dev/null && {
+  egrep -q "^FAIL .+" <<<"$stdout" >/dev/null && {
     PASS "stdout contains the FAIL statement when $case"
   } || {
     FAIL --next "stdout should contain the FAIL statement when $case"
+    dry-diagnose "stdout"
+  }
+}
+
+function success () {
+  dry-assert-code 0
+  dry-refute-output "stderr"
+  test $(wc -l <<<"$stdout") -eq 1 &&  {
+    PASS "outputs exactly ONE line on stdout when $case"
+  } || {
+    FAIL --next "should output exactly ONE line on stdout when $case"
+    dry-diagnose "stdout"
+  }
+  egrep -q "^PASS .+" <<<"$stdout" >/dev/null && {
+    PASS "stdout contains the PASS statement when $case"
+  } || {
+    FAIL --next "stdout should contain the PASS statement when $case"
     dry-diagnose "stdout"
   }
 }
@@ -75,9 +92,26 @@ case "$1" in
     $0 usage ": --returns ''" "[value] is empty string"
 
     $0 failure "false --returns zero" \
-      "[value] is 'zero' but command is false"
+      "[value] is 'zero', command is false"
     $0 failure "true --returns non-zero" \
-      "[value] is 'non-zero' but command is true"
+      "[value] is 'non-zero', command is true"
+    $0 failure "true --returns nonzero" \
+      "[value] is 'nonzero', command is true"
+    $0 failure "false --returns 13" \
+      "[value] is '13', command is false"
+    $0 failure "true --returns 51" \
+      "[value] is '51', command is true"
+
+    $0 success "true --returns zero" \
+      "[value] is 'zero', command is true"
+    $0 success "false --returns non-zero" \
+      "[value] is 'non-zero', command is true"
+    $0 success "false --returns nonzero" \
+      "[value] is 'nonzero', command is true"
+    $0 success "exit 13 --returns 13" \
+      "[value] is '13', command is 'exit 13'"
+    $0 success "exit 3 --returns -lt 5" \
+      "[value] is '-lt 5', command is 'exit 3'"
     ;;
   dry-*)
     echo "Bad usage: '$1' is not a valid test unit" >&2
@@ -85,7 +119,7 @@ case "$1" in
     ;;
   *)
     unit="$1"
-    test $(type -t "$unit") != 'function' && {
+    test "$(type -t "$unit")" != 'function' && {
       echo "Bad usage: test unit '$unit' is not defined"
       exit 2
     } >&2
