update check--returns test script, well polished now

diff --git a/test/check--returns b/test/check--returns
--- a/test/check--returns
+++ b/test/check--returns
@@ -1,43 +1,76 @@
 #!/bin/bash
 
-source autotest
+case "$1" in
+  '') # runs all test cases
+    codes=0
+    RUN () { "$0" "all=$1"; codes+=$?; }
+    for unit in {usage,failure,success}; do RUN "$unit"; done
+    exit $(( $codes ))
+    ;;
+  all=?*) # runs all cases for that unit
+    unit="${1#all=}"; codes=0
+    CASE () { "$0" "unit=$unit" "$@"; codes+=$?; }
 
-autotest load check-command
-autotest load check-command--returns
+    case "$unit" in
+      usage) #cases that should fail with EUSAGE
+        CASE : \; --returns # missing [value]
+        CASE : \; --returns '' # [value] is empty string
+        CASE : \; --returns 0 13 # two integer parameters
+        ;;
+      failure) #cases that should fail with code 1 (FAIL)
+        CASE false \; --returns zero
+        CASE true \; --returns non-zero
+        CASE true \; --returns nonzero
+        CASE false \; --returns 13
+        CASE true \; --returns 51
+        ;;
+      success) #cases that should succed
+        CASE true \; --returns zero
+        CASE false \; --returns non-zero
+        CASE false \; --returns nonzero
+        CASE exit 13 \; --returns 13
+        CASE exit 3 \; --returns -lt 5
+        ;;
+      *)
+        echo "Bad usage: '$unit' has no cases defined" >&2
+        exit 2
+        ;;
+    esac
+    exit $(( $codes ))
+    ;;
+  unit=?*) ;; # let main() run
+  *)
+    echo "Bad usage: invalid argument '$1'" >&2
+    exit 2
+    ;;
+esac
 
-function dry-assert-code () {
-  test "$code" -eq $1 && {
-    PASS "code is $1 when $case"
-  } || {
-    FAIL --next "code should be $1 when $case, but returns $code"
-  }
+function main () {
+  unit="${1#unit=}"
+  test "$(type -t "$unit")" != 'function' && {
+    echo "Bad usage: test unit '$unit' is not defined"
+    exit 2
+  } >&2
+
+  source autotest
+  source "$(autotest--root)/test/dry-assert.bash"
+  autotest load check-command
+  autotest load check-command--returns
+
+  shift
+  echo "TEST $0 unit=$unit $@"
+  case="running check command with argv '$@'"
+
+  stdout="$( check-command "$@" 2>/dev/null )"
+  stderr="$( check-command "$@" 2>&1 >/dev/null )"
+  code=$?
+
+  $unit "$@"
+  code=$?
+  echo CODE $code
+  exit $code
 }
-function dry-diagnose () {
-  test -v "${1:?missing output variable name}"
-  while read l; do
-    echo "   | ${1#std}: $l"
-  done <<<"${!1}" >&2
-  code=1
-}
-function dry-assert-output () {
-  test -v "${1:?missing output variable name}"
-  test -n "${!1}" && {
-    PASS "$1 has data when $case"
-  } || {
-    FAIL --next "$1 should have data when $case"
-    return 1
-  }
-}
-function dry-refute-output () {
-  test -v "${1:?missing output variable name}"
-  test -z "${!1}" && {
-    PASS "$1 has no data when $case"
-  } || {
-    FAIL --next "$1 should have no data when $case"
-    dry-diagnose "$1"
-    return 1
-  }
-}
+
 
 function usage () {
   dry-assert-code 2
@@ -85,69 +118,7 @@ function success () {
   }
 }
 
-case "$1" in
-  # run all test cases
-  '')
-    $0 usage ": --returns" "missing [value]"
-    $0 usage ": --returns ''" "[value] is empty string"
-
-    $0 failure "false --returns zero" \
-      "[value] is 'zero', command is false"
-    $0 failure "true --returns non-zero" \
-      "[value] is 'non-zero', command is true"
-    $0 failure "true --returns nonzero" \
-      "[value] is 'nonzero', command is true"
-    $0 failure "false --returns 13" \
-      "[value] is '13', command is false"
-    $0 failure "true --returns 51" \
-      "[value] is '51', command is true"
-
-    $0 success "true --returns zero" \
-      "[value] is 'zero', command is true"
-    $0 success "false --returns non-zero" \
-      "[value] is 'non-zero', command is true"
-    $0 success "false --returns nonzero" \
-      "[value] is 'nonzero', command is true"
-    $0 success "exit 13 --returns 13" \
-      "[value] is '13', command is 'exit 13'"
-    $0 success "exit 3 --returns -lt 5" \
-      "[value] is '-lt 5', command is 'exit 3'"
-    ;;
-  dry-*)
-    echo "Bad usage: '$1' is not a valid test unit" >&2
-    exit 2
-    ;;
-  *)
-    unit="$1"
-    test "$(type -t "$unit")" != 'function' && {
-      echo "Bad usage: test unit '$unit' is not defined"
-      exit 2
-    } >&2
-    
-    shift
-    argv="${1:?missing check-command argument list}"
-    case="${2:?missing $unit case description}"
-
-    stdout="$( check-command $argv 2>/dev/null )"
-    stderr="$( check-command $argv 2>&1 >/dev/null )"
-    code=$?
-
-    echo "TEST $0 $unit '$argv' '$case'"
-    $unit "$@"
-    code=$?
-    echo CODE $code
-    exit $code
-    ;;
-esac
-
-function dry-assert-equal () {
-  test "$1" = "$2" && {
-    PASS "value '$1' is equal to '$2'"
-  } || {
-    caller 0 >&2
-    FAIL "actual value is '$1' but expected it to be '$2'"
-  }
-}
+main "$@"
 
 ##
 # vim modeline
