split-out autotest executable file on multiple *.bash files

diff --git a/autotest b/autotest
--- a/autotest
+++ b/autotest
@@ -1,20 +1,140 @@
 #!/bin/bash
 
-# outputs the autotest root directory
-function autotest--root () { dirname "$(realpath "$0")"; }
-
-# outputs the autotest usage help
-function autotest--help () { source "$(autotest root)/README.bash" "$@"; }
-
-# outputs all autotest api source code to stdout
-# TODO testodo <<<"tool to report tests pending to write"
-function autotest--source () {
-  find "$(autotest--root)/api-old" -name "*.bash" -type f -exec cat '{}' +
+function autotest--root () {
+  # outputs the autotest root directory
+  AUTOTEST_ROOT="$(dirname "$(readlink -f "$BASH_SOURCE")")"
+  autotest--root () { echo "$AUTOTEST_ROOT"; }
 }
+
+function autotest--source () {
+  # outputs all autotest old-api source code to stdout
+  # TODO testodo <<<"tool to report tests pending to write"
+  find "$(autotest--root)/old-api" -name "*.bash" -type f -exec cat '{}' +
+}
+
+function autotest () {
+  # dumb function which bypasses old-api tests
+  autotest--source
+}
+
+function PASS () {
+  echo PASS "$@" 
+}
+function PASS--test () {
+  # usage: PASS--test [function_name]
+  # tests specified [function_name] echoes PASS "$@" and continues
+  # function name defaults to PASS
+  # > - Cowboy: Is this really need?
+  # > - Wiseman: Yes, no tests provide no good features
+  local func="${1:-PASS}"
+  ( #to avoid pollution
+    echo "TEST autotest $FUNCNAME $1"
+    pass () { echo "PASS $FUNCNAME: '$func' $@"; }
+    fail () { echo "FAIL $FUNCNAME: '$func' $@"; exit 1; }
+
+    stdout="$( "$func" $FUNCNAME 2>/dev/null; echo continues)"
+    code=$?
+
+    [[ "$stdout" =~ continues$ ]] \
+      && pass "does not exit subshell" \
+      || fail "makes subshell exit"
+
+    test $code -eq 0 \
+      && pass "exit code should be 0" \
+      || fail "exit code is not 0 (is $code)"
+
+    [[ "$stdout" =~ ^PASS ]] \
+      && pass "stdout begins with PASS" \
+      || fail "'$stdout' does not begin with 'PASS'" \
+
+    test "$($func $FUNCNAME)" = 'PASS' \
+      && fail "stdout is just 'PASS'" \
+      || pass "stdout is not just 'PASS'" \
+
+    test $( $func $FUNCNAME 2>/dev/null | wc -l ) -ne 1 \
+      && fail "should write ONE line to stdout" \
+      || pass "writes one line to stdout"
+
+    echo "CODE 0"
+    exit 0 #to be explicit
+  )
+  return $? #to be explicit
+}
+function FAIL () {
+  # usage: FAIL [code]? [arguments]{0,n}
+  # echoes specified [arguments] to standard output and exits with code 1
+  # TODO if [code] is known (see `autocode`), exits with that code instead
+  echo FAIL "$@"
+  echo CODE 1
+  exit 1
+}
+function FAIL--test () {
+  # usage: FAIL--test [function_name]
+  # tests specified [function_name] echoes FAIL "$@" and exits with code > 0
+  # function name defaults to FAIL
+  # > - Cowboy: Is this really need?
+  # > - Wiseman: Yes, no tests provide no good features
+
+  local func="${1:-FAIL}"
+  ( #to avoid pollution
+    echo "TEST autotest $FUNCNAME $1"
+    pass () { echo "PASS '$func' $@"; }
+    fail () { echo "FAIL '$func' $@"; exit 1; }
+
+    test "$(type -t "$func")" != 'function' \
+      && fail "should be a function" \
+      || pass "is a function"
+
+    stdout="$( "$func" $FUNCNAME 2>/dev/null; echo continues)"
+    code=$?
+
+    [[ "$stdout" =~ continues$ ]] \
+      && fail "should had exit subshell" \
+      || pass "makes subshell exit"
+
+    test $code -eq 0 \
+      && fail "exit code should NOT be 0" \
+      || pass "exit code is not 0"
+
+    stdout="$( $func $FUNCNAME 2>/dev/null)"
+    test $( wc -l <<<"$stdout" ) -ne 2 \
+      && fail "should write TWO lines to stdout" \
+      || pass "writes TWO lines to stdout"
+
+    for n in {1,2}; do
+      read line
+      case $n in
+        1)
+          test "$line" != "FAIL $FUNCNAME" \
+            && fail "line 1 is not 'FAIL $FUNCNAME'" \
+            || pass "line 1 is 'FAIL $FUNCNAME'"
+          ;;
+        2)
+          test "$line" != "CODE 1" \
+            && fail "line 2 is not 'CODE 1'" \
+            || pass "line 2 is 'FAIL $FUNCNAME'"
+          ;;
+      esac
+    done <<<"$stdout"
+
+    echo "CODE 0"
+    exit 0 #to be explicit
+  )
+  return $? #to be explicit
+}
+
+function load () { echo "not implemented"; exit 1; }
+
+test "$0" != "$BASH_SOURCE" && return 0
 
 # autotest source code  is sent to stdout when this script receives 0 arguments
 # this is done early because no more functions are need to perform this task
 (( $# )) || { autotest--source; exit $?; }
+
+function autotest--help () {
+  # outputs the autotest usage help
+  source "$(autotest--root)/README.sh" "$@";
+}
 
 # some subcomands can be run now to speed-up them
 case "$1" in
@@ -27,144 +147,25 @@ esac
 ##
 
 # Logging functions
-function emsg () { echo "$(basename $0):" "$@"; } >&2 # better than >&2 echo
+function emsg () {
+  echo "$(basename "$BASH_SOURCE"):" "$@"
+} >&2 # better than >&2 echo
 function verb () { :; } # meant for debugging. Uncomment line below to activate
 #function verb () { emsg "debug: $(caller 0):" "$@"; }
 
 # helper to fail fast
-function fail () { emsg "${1:?'missing message'}"; exit ${2:?'missing code'}; }
-
-# Tells whenever given value ($1) is an integer
-is_int () { case "${1#[-]}" in ''|*[!0-9]*) return 1;; *) return 0;; esac; }
-
-##
-# THE AUTOTEST PROTOCOL (ATP)
-#
-# TODO write about present and future
-# TODO i.e. "PLAN statement", "TIME statement", etc...
-#
-# > Be able to gracefully handle future upgrades, being forward compatible.
-# >   - Ignore unknown directives
-# >   - Ignore any unparsable lines
-# >
-# > > inspired by http://testanything.org/philosophy.html
-##
-
-# maps known exit status codes to codenames and vice-versa
-function autocode () {
-  (( $# > 1 )) && fail "$FUNCNAME expects ONE or NONE arguments" 2
-  case ${1^^} in
-    '')
-      for i in {0..255}; do
-        autocode $i &>/dev/null && printf "$i → %s\n" "$(autocode $i)"
-      done
-      return 1
-      ;;
-    0) echo OK      ;; OK)     echo 0   ;; # success code
-    1) echo FAIL    ;; FAIL)   echo 1   ;; # generic failure code
-    2) echo EUSAGE  ;; EUSAGE) echo 2   ;; # incorrect command ussage
-    3) echo EXCODE  ;; EXCODE) echo 3   ;; # invalid exit status code
-    # reserve through 9
-    #[4-9]) echo ETEST"autotest protocol error (reserved)" ;;
-    10) echo EATEST ;; EATEST) echo 10  ;; # Autotest Syntax Error
-    11) echo EAOPEN ;; EAOPEN) echo 11  ;; # Open TEST unit (missing CODE)
-    12) echo EAVOID ;; EAVOID) echo 12  ;; # Void TEST unit (nothing inside)
-    13) echo EACODE ;; EACODE) echo 13  ;; # CODE statement exit status mismatch
-    14) echo EAFLOW ;; EAFLOW) echo 14  ;; # unexpected statement (premature)
-    # special cases
-    124) echo EATIME;; EATIME) echo 124 ;; # operation timeout
-    126) echo EACCES;; EACCES) echo 126 ;; # can't execute (no permission)
-    127) echo ENOENT;; ENOENT) echo 127 ;; # entity not found (file/dir/...)
-    # signals are 129 through 192 (128 + signal code)
-    SIG*) echo $(( 128 + $(kill -l $1) )) ;;
-    160|161) echo $1; return 1 ;; # TODO why signals 32 and 33 don't exist?
-    129|1[3-8][0-9]|19[0-2])
-      echo "SIG$(kill -l $(($1-128)))" ;;
-    *)
-      is_int "$1" && (($1 >  255)) && fail "code '$1' invalid" 2;
-      echo "$1"
-      emsg "no error code information for '$1'"
-      return 1
-      ;;
-  esac
+function fail () {
+  code=$(autocode "${1:?'missing exit code'}") || exit
+  emsg "$1: ${2:?'missing message'}"
+  exit $code
 }
 
+source "$(autotest--root)/api/autocode.bash"
 # run autocode subcommand ASAP to speed it up a bit
 case "$1" in code) shift; autocode "$@"; exit; esac
 
-# pass-through stdin data to stdout, but ensure its syntax matches ATP
-function autotext () {
-  local FAILS=0 FAILED=0 TESTS=0 CODES=0 COUNT=0 
-  local ETC CODE READCODE
-  while read -t 2 KEY VAL; READCODE=$?
-  do # each line consists of a leading KEYWORD with VALUE data
-    case "$KEY" in
-      TEST)
-        verb "TEST hit with codes=$CODES tests=$TESTS"
-        (($CODES == $TESTS)) || return $(autocode EAOPEN)
-        let TESTS++; FAILS=0; COUNT=0
-        ;;
-      FAIL|PASS|SKIP)
-        (($CODES == $TESTS)) && return $(autocode EAFLOW)
-        case $KEY in FAIL) let FAILS++;; PASS) let COUNT++;; esac
-        ;;
-      #SKIP) : ;;
-      CODE)
-        verb "CODE hit with codes=$CODES tests=$TESTS"
-        case "${VAL}" in
-          '') # empty status code means "generate a code now"
-            verb "generate code, count=$COUNT fails=$FAILS"
-            VAL="$(autocode OK) OK"
-            (($COUNT)) || VAL="$(autocode EAVOID) EAVOID"
-            (($FAILS)) && VAL="$(autocode FAIL) FAIL"
-            ;;
-        esac
-        read CODE ETC <<<"$VAL"
-        is_int $CODE && (($CODE < 256)) || return $(autocode EXCODE)
-        let CODES++; (($CODES == $TESTS )) || return $(autocode EAFLOW)
-        # statement was succesfully validated
-        verb "statement is code=$CODE etc='$ETC', fails=$FAILS, count=$COUNT"
-        ;;
-      '') # did not find a way to work with read code outside while loop
-        verb "read key=$KEY code=$READCODE"
-        test $READCODE -eq 1 && break # presumably, we hit end-of-file
-        test $READCODE -gt 128 && {
-          echo "CODE $(autocode EATIME)"
-          return $(autocode EATIME)
-        }
-        return $(autocode EATEST) # if it's not timeout, it's syntax error
-        ;;
-      *) return $(autocode EATEST) ;;
-    esac
-    # pass data down through pipeline, done if KEYWORD != CODE
-    echo "$KEY $VAL"; test "$KEY" != "CODE" && continue
-    # decide if parsing process should continue
-    case "$(autocode $CODE)" in
-      OK) # reported success, but ensure it's correct
-        (($FAILS)) && return $(autocode EACODE)
-        (($COUNT)) || return $(autocode EAVOID)
-        ;;
-      EAVOID|EATIME) break ;; # stop parsing
-      *) # reported failure, but ensure it's correct
-        (($FAILS)) || return $(autocode EACODE)
-        #((COUNT + FAILS)) || return $(autocode EAVOID)
-        let FAILED++
-        ;;
-    esac
-  done
-  verb "generate return tests=$TESTS codes=$CODES"
-
-  (( TESTS - CODES )) && return $(autocode EAOPEN)
-  verb "generate return tests=$TESTS"
-  (( $TESTS )) || return $(autocode EAVOID)
-  verb "generate return code=$CODE"
-  (( $CODE )) && return $CODE
-  verb "generate return failed=$FAILED"
-  (( $FAILED )) && return $(autocode FAIL)
-  return $CODE 
-}
-
-# some subcommands can be run here to speed' em up a bit
+source "$(autotest--root)/api/autotext.bash"
+# this subcommands can be run here to speed' em up a bit
 case "$*" in
   -) autotext; exit ;;
   'report '*)
@@ -192,183 +193,25 @@ case "$*" in
     ;;
 esac
 
+source "$(autotest--root)/api/autoexec.bash"
+
 ##
 # TEST RUNNER ROUTINE: given a file as argument 1
 ##
 if test -f "$1"
 then # autotest <FILE> [ARG .. LIST] should be handled here
-  test -x "$1" || fail "EACCES: '$1' is not executable" $(autocode EACCES)
-  # CARE: autotest <FILE> should output valid Autotest Protocol
-  {
-    ( # run within subshell to catch allways a code
-      "$1"
-      #code=$?
-      #exit $code
-    )
-    exit $? # exit with catched code to pass through PIPESTATUS
-  } | autotext
-  TEST_CODE="${PIPESTATUS[0]}" AUTO_CODE="${PIPESTATUS[1]}" TESTSEC=$SECONDS
- 
-  if (( TEST_CODE + AUTO_CODE == 0 )); then exit 0; fi
-
-  case "$(autocode $AUTO_CODE)" in
-    #FAIL) ! (($TEST_CODE)) && exit $(autocode FAIL) ;;
-    EAOPEN)
-      verb "automatically closing because got EAOPEN"
-      printf "CODE "
-      (($TEST_CODE)) && printf "%s" $TEST_CODE || printf "%s" $AUTO_CODE
-      echo " (generated by $0 $*)"
-      ;;
-  esac
-    
-  # now is safe to review the result
-  echo "TEST $0" "$@"
-
-  if (($TEST_CODE)); then # test run reported error
-    autocode $TEST_CODE &>/dev/null \
-      && echo "FAIL test run exit status was $(autocode $TEST_CODE)" \
-      || echo "FAIL test run exit status $TEST_CODE is not known by autocode"
-    (($TESTSEC < $AUTOSEC)) && printf PASS || printf FAIL
-    echo " test run took $TESTSEC seconds (expecting ${AUTOSEC} seconds max)"
-    #echo "CODE $TEST_CODE"; exit $TEST_CODE
-  else
-    echo "PASS test run suceed with exit status 0"
-  fi
-
-  if (($AUTO_CODE)); then # autotext reported error
-    autocode $AUTO_CODE &>/dev/null \
-      && echo "FAIL autotext exit status was $(autocode $AUTO_CODE)" \
-      || echo "FAIL autotext exit status $AUTO_CODE is not known by autocode"
-  else
-    echo "PASS autotext suceed with exit status 0"
-  fi
-
-  if (($TEST_CODE == $AUTO_CODE)); then
-    echo "PASS test run exit status was $TEST_CODE, expected $AUTO_CODE"
-  else
-    # CARE must be taken when codes differ, so let's use a case-by-case aproach
-    # TODO THIS SHIT IS FUCKING UGLY AND NO ELEGANT, FUCK OFF AND START AGAIN
-    if (($TEST_CODE==$(autocode OK))) || (($TEST_CODE==$(autocode SIGPIPE)))
-    then
-      case "$(autocode $AUTO_CODE)" in
-        FAIL) echo "FAIL test run '$1' failed" ;;
-        EXCODE) echo "FAIL test run '$1' produced an invalid CODE statement" ;;
-        EATEST) echo "FAIL test run '$1' produced invalid ATP syntax" ;;
-        EATIME) echo "FAIL test run '$1' timed out"; TEST_CODE=0 ;;
-        *) echo "FAIL unexpected autotext exit code $(autocode $AUTO_CODE)" ;;
-      esac
-    elif (($TEST_CODE==$(autocode ENOENT)))&&(($AUTO_CODE==$(autocode EAVOID)))
-    then echo "FAIL file '$1' does not exist"
-    elif (($TEST_CODE==$(autocode EACCES)))&&(($AUTO_CODE==$(autocode EAVOID)))
-    then echo "FAIL user '$USER' can't execute '$1'"
-    elif (($TEST_CODE==$(autocode SIGTERM)))&&(($AUTO_CODE==$(autocode EAOPEN))) \
-      || (($TEST_CODE==$(autocode SIGKILL)))&&(($AUTO_CODE==$(autocode EAOPEN)))
-    then
-      echo "FAIL test run '$1' timed out"
-      verb "force EATIME"; TEST_CODE=$(autocode EATIME)
-    else
-      echo "FAIL code mismatch: $(autocode $TEST_CODE)!=$(autocode $AUTO_CODE)"
-      verb "force EACODE"; TEST_CODE=0 AUTO_CODE=$(autocode EACODE)
-    fi
-  fi
-
-  # if test execution script failed, that's the code to be reported
-  printf "CODE "; (($TEST_CODE)) && echo $TEST_CODE || echo $AUTO_CODE
-
-  verb "will exit now, test_code=$TEST_CODE, auto_code=$AUTO_CODE"
-  if (($TEST_CODE != 0)); then exit $TEST_CODE; else exit $AUTO_CODE; fi
+  autoexec "$@"
+  exit $?
 fi
 
 ##
 # TRASHCAN HEREAFTER
 ##
-
-# pass-through stdin data to stdout, but ensure its syntax matches ATP
-function autotest--protocol.v1 () {
-  local tlvl=0 clvl=0 count=0 fails=0 code=0 failed=0
-  while read KEY value; do
-    case $KEY in
-      TEST)
-        if test $tlvl -eq $clvl; then let tlvl++; else
-          emsg "EATEST: premature 'TEST $value' statement (expecting CODE)"
-          return 5
-        fi
-        read -d ' ' filepath <<<"$value"
-        if ! test -f "$filepath"; then
-          emsg "EATEST: '$filepath' is not a file"
-          return 127
-        fi
-        emsg "debug autotest: tlvl=$tlvl; reset count, fails, code"
-        count=0 fails=0 code=0
-        ;;
-      FAIL|PASS|SKIP)
-        if test $clvl -eq $tlvl; then
-          emsg "EATEST: premature '$KEY $value' statement (expecting TEST)"
-          return 5
-        fi
-        (( count++ ))
-        test "$KEY" == "FAIL" && (( fails++ ))
-        ;;
-      CODE)
-        if test $clvl -lt $tlvl; then let clvl++; else
-          emsg "EATEST: premature 'CODE $value' statement (expecting TEST)"
-          return 34
-        fi
-        read -d ' ' code <<<"$value"
-        if ! is_int "$code" || test $code -gt 255; then
-          #echo "CODE 2${value##$code}"
-          emsg "EATEST: invalid code '$code'"
-          return 44
-        fi
-        # remember how many CODE statements report a failure
-        if test $code -gt 0; then let failed++; fi
-        if test $count -eq 0
-        then # test ended without any assertion statement
-          echo "FAIL there are no assertions in this test"
-          (( failed++ ))
-          echo "CODE 1${value##$code}" # TODO code empty
-          continue #parsing but don't pass-trough
-        elif test $code -eq 0 && test $fails -gt 0
-        then # code is 0 but there are failures
-          echo "FAIL test exit status code was 0 with $fails failures"
-          (( failed++ ))
-          echo "CODE 1${value##$code}"
-          continue #parsing but don't pass-trough
-        elif test $code -eq 0 && test $failed
-        then # code is 0 but some previous test units failed
-          emsg "FAIL there are $failed test unit failures above"
-          (( failed++ ))
-          echo "CODE 1${value##$code}"
-          continue #parsing but don't pass-trough
-        else
-          emsg "debug autotest: code=$code count=$count fails=$fails failed=$failed"
-        fi
-        ;;
-      *) emsg "bad syntax: '$keyword $value'"; return 5 ;;
-    esac
-    echo "$KEY $value" # pass data down through pipeline
-  done
-  if test $tlvl -eq 0 ; then
-    emsg "EATEST: expecting at least one TEST statement"
-    return 5
-  fi
-  # when the last CODE statement is missing, generate one
-  if ! test $tlvl -eq $clvl; then
-    emsg "debug autotest: generate CODE count=$count fails=$fails failed=$failed"
-    if ! (($count)); then echo "FAIL empty test"; code=3
-    elif (($fails)); then code=1
-    elif (($failed)); then echo "FAIL a previous unit failed"; code=1
-    fi
-    echo "CODE $code"
-  fi
-  return $code # return the last stored code allways
-}
-
 case "$1" in
   checkup)
     # TODO define after, this should be refactored
     # TODO replace this and use 1 file and {brace,expansion} instead?
-    find "$(autotest--root)/api-old" -name "*.bash" -type f -exec bash -c '
+    find "$(autotest--root)/old-api" -name "*.bash" -type f -exec bash -c '
       file={}
       tool=${file##*/}
       tool=${tool%%.bash}
