huge commit for autotest, but not fighting the cowboy. GO with autoTEXT examples, and test autotext <FILE before autotest <FILE>

diff --git a/autotest b/autotest
--- a/autotest
+++ b/autotest
@@ -142,15 +142,12 @@ function autocode () {
   fi
   case ${1^^} in
 #    ABOVE) echo 11 ;; 11) echo "some test unit failed above" ;;
-#    # reserve through 19
 #    # autotest protocol syntax errors
 #    TFLOW) echo 21 ;; 26) echo "premature TEST statement" ;;
 #    CFLOW) echo 22 ;; 22) echo "premature CODE statement" ;;
 #    FFLOW) echo 23 ;; 23) echo "premature FAIL statement" ;;
 #    PFLOW) echo 24 ;; 24) echo "premature PASS statement" ;;
 #    SFLOW) echo 25 ;; 25) echo "premature SKIP statement" ;;
-#    FINAL) echo 26 ;; 26) echo "FINAL" # missing final CODE statement
-#    FIRST) echo 27 ;; 27) echo "missing the first TEST statement" ;;
 #    # special cases
 #    TODO|IMPLEMENTATION) echo 255 ;; 255) echo "implementation error" ;;
     '')
@@ -165,15 +162,20 @@ function autocode () {
     3) echo EXCODE  ;; EXCODE) echo 3   ;; # invalid exit status code
     # reserve through 9
     10) echo EATEST ;; EATEST) echo 10  ;; # Autotest Syntax Error
-    11) echo EAOPEN ;; EAOPEN) echo 11  ;; # Open TEST unit (missing final CODE)
+    11) echo EAOPEN ;; EAOPEN) echo 11  ;; # Open TEST unit (missing CODE)
     12) echo EAVOID ;; EAVOID) echo 12  ;; # Void TEST unit (nothing inside)
     13) echo EACODE ;; EACODE) echo 13  ;; # CODE statement exit status mismatch
-    126) echo EACCES;; EAFILE) echo 126 ;; # can't execute (no permission)
-    127) echo ENOENT;; ENOENT) echo 127 ;; # executable not found
+    14) echo EAFLOW ;; EAFLOW) echo 14  ;; # unexpected statement (premature)
+    # special cases
+    124) echo EATIME;; EATIME) echo 124 ;; # operation timeout
+    126) echo EACCES;; EACCES) echo 126 ;; # can't execute (no permission)
+    127) echo ENOENT;; ENOENT) echo 127 ;; # entity not found (file/dir/...)
     #[1-3]|3[0-9]) echo ETEST"autotest protocol error (reserved)" ;;
     # signals are 129 through 192 (128 + signal code
     SIG*) echo $(( 128 + $(kill -l $1) )) ;;
-    129|1[3-8][0-9]|19[0-2]) echo "SIG$(kill -l $(($1-128)))" ;;
+    160|161) echo $1; return 1 ;; # why signals 32 and 33 don't exist?
+    129|1[3-8][0-9]|19[0-2])
+      echo "SIG$(kill -l $(($1-128)))" ;;
     *)
       is_int "$1" && (($1 >  255)) && emsg "code '$1' invalid" && return 2
       echo "$1"
@@ -186,40 +188,70 @@ function autocode () {
 # pass-through stdin data to stdout, but ensure its syntax matches ATP
 function autotext () {
   local FAILS=0 FAILED=0 TESTS=0 CODES=0 COUNT=0 
-  local ETC CODE
-  while read KEY VAL
+  local ETC CODE READCODE
+  while read -t 2 KEY VAL; READCODE=$?
   do # each line consists of a leading KEYWORD with VALUE data
     case "$KEY" in
-      TEST) let TESTS++ ;;
-      FAIL) let FAILS++ ;;
-      PASS) let COUNT++ ;;
+      TEST)
+        verb "TEST hit with codes=$CODES tests=$TESTS"
+        (($CODES == $TESTS)) || return $(autocode EAOPEN)
+        let TESTS++; FAILS=0; COUNT=0
+        ;;
+      FAIL|PASS|SKIP)
+        (($CODES == $TESTS)) && return $(autocode EAFLOW)
+        case $KEY in FAIL) let FAILS++;; PASS) let COUNT++;; esac
+        ;;
+      #SKIP) : ;;
       CODE)
+        verb "CODE hit with codes=$CODES tests=$TESTS"
         case "${VAL}" in
           '') # empty status code means "generate a code now"
-            verb "generate code fails=$FAILS"
+            verb "generate code, count=$COUNT fails=$FAILS"
             VAL=$(autocode OK)
+            (($COUNT)) || VAL=$(autocode EAVOID)
             (($FAILS)) && VAL=$(autocode FAIL)
-            ;;
-          [0-9]|[0-9][0-9]|[1-2][0-9][0-9])
-            verb "not int code"
             ;;
         esac
         read CODE ETC <<<"$VAL"
-        verb "statement is code=$CODE etc='$ETC'"
-        #autocode $CODE >/dev/null || return
-        #test -n "$ETC" && { is_int "$ETC" || return $(autocode EXCODE); }
-        ! (($CODE)) && (($FAILS)) && return $(autocode EACODE)
-        (( $CODE )) && let FAILED++
-        let CODES++
+        is_int $CODE && (($CODE < 256)) || return $(autocode EXCODE)
+        let CODES++; (($CODES == $TESTS )) || return $(autocode EAFLOW)
+        # statement was succesfully validated
+        verb "statement is code=$CODE etc='$ETC', fails=$FAILS, count=$COUNT"
+        ;;
+      '') # did not find a way to work with read code outside while loop
+        verb "read key=$KEY code=$READCODE"
+        test $READCODE -gt 128 && {
+          echo "CODE $(autocode EATIME)"
+          return $(autocode EATIME)
+        }
+        return $(autocode EATEST) # if it's not timeout, it's syntax error
+        ;;
+      *) return $(autocode EATEST) ;;
+    esac
+    # pass data down through pipeline, done if KEYWORD != CODE
+    echo "$KEY $VAL"; test "$KEY" != "CODE" && continue
+    # decide if parsing process should continue
+    case "$(autocode $CODE)" in
+      OK) # reported success, but ensure it's correct
+        (($FAILS)) && return $(autocode EACODE)
+        (($COUNT)) || return $(autocode EAVOID)
+        ;;
+      EAVOID|EATIME) break ;; # stop parsing
+      *) # reported failure, but ensure it's correct
+        (($FAILS)) || return $(autocode EACODE)
+        #((COUNT + FAILS)) || return $(autocode EAVOID)
+        let FAILED++
         ;;
     esac
-    echo "$KEY $VAL" # pass data down through pipeline
   done
   verb "generate return tests=$TESTS codes=$CODES"
+
   (( TESTS - CODES )) && return $(autocode EAOPEN)
-  verb "generate return count=$COUNT fails=$FAILS"
-  (( COUNT + FAILS )) || return $(autocode EAVOID)
-  verb "generate return failed=$FAILED code=$CODE"
+  verb "generate return tests=$TESTS"
+  (( $TESTS )) || return $(autocode EAVOID)
+  verb "generate return code=$CODE"
+  (( $CODE )) && return $CODE
+  verb "generate return failed=$FAILED"
   (( $FAILED )) && return $(autocode FAIL)
   return $CODE 
 }
@@ -238,9 +270,10 @@ case "$1" in
     test $# -eq 2 || autofail "expecting two arguments" 2
     test -f "$2" || autofail "'$2' is not a file" 127
     # generate report discarding all stderr
-    autotest "$2"  2>/dev/null | autotest--protocol.v1 2>/dev/null
+    #autotest "$2"  2>/dev/null | autotest--protocol.v1 2>/dev/null
+    autotest "$2"  2>/dev/null
     exit $? # preserve report exit status
-  ;;
+    ;;
   checkup)
     # TODO define after, this should be refactored
     # TODO replace this and use 1 file and {brace,expansion} instead?
@@ -258,78 +291,96 @@ case "$1" in
     source <(autotest)
     tested "autotest can be sourced with process substitution"
     exit $?
-  ;;
+    ;;
   *)
     # autotest <SUBCOMMAND> <FILE> should be not handled here
     # CARE: don't print help to stdout when there is an error!
     if (( $# > 1 )); then autotest--help >&2; exit $(autocode EUSAGE); fi
     # CARE: autotest <FILE> should output valid Autotest Protocol
-    # ¿¿¿also when <FILE> does not exist????, so
-    #if ! test -f "$1"; then : ; fi
+    # also when <FILE> does not exist????, so
   ##
   # TEST RUNNER ROUTINE: given a file as argument 1
   ##
-  AUTOSEC=3
+  AUTOSEC=9
   SECONDS=0
   {
-    ( # run within subshell to catch allways a code
+    #( # run within subshell to catch allways a code
       # use timeout to avoid running forever if the test hangs
       timeout --preserve-status -v $AUTOSEC "$1"
-      code=$?
-      case $code in
-        126) printf "TEST $1\nFAIL $USER can't execute '$1'\nCODE 126\n" ;;
-        127) printf "TEST $1\nFAIL '$1' does not exist \nCODE 127\n" ;;
-      esac
-      exit $code
-    )
+      #code=$?
+      #exit $code
+    #)
     exit $? # exit with catched code to pass through PIPESTATUS
   } | autotext
-
-  TEST_CODE="${PIPESTATUS[0]}" AUTO_CODE="${PIPESTATUS[1]}"
+  TEST_CODE="${PIPESTATUS[0]}" AUTO_CODE="${PIPESTATUS[1]}" TESTSEC=$SECONDS
+  
+  #if !(($TEST_CODE)) && !(($AUTO_CODE)); then exit; fi
 
   case "$(autocode $AUTO_CODE)" in
+    #FAIL) ! (($TEST_CODE)) && exit $(autocode FAIL) ;;
     EAOPEN)
-      echo "CODE $TEST_CODE"
-      (($TEST_CODE)) && AUTO_CODE=0
+      verb "automatically closing because got EAOPEN"
+      printf "CODE "
+      (($TEST_CODE)) && printf "%s" $TEST_CODE || printf "%s" $AUTO_CODE
+      echo " (generated by $0 $*)"
       ;;
   esac
- 
-  if !(($TEST_CODE)) && !(($AUTO_CODE)); then exit; fi
-
+    
   # now is safe to review the result
-  echo "TEST $0 $1"
+  echo "TEST $0" "$@"
 
-  (($SECONDS < $AUTOSEC)) \
-    && echo "PASS test ran within the ${AUTOSEC}s seconds limit" \
-    || echo "FAIL test run took ${SECONDS}s, expecting ${AUTOSEC}s max"
-
-  if (($TEST_CODE)); then # test run reported a failure
+  if (($TEST_CODE)); then # test run reported error
     autocode $TEST_CODE &>/dev/null \
       && echo "FAIL test run exit status was $(autocode $TEST_CODE)" \
       || echo "FAIL test run exit status $TEST_CODE is not known by autocode"
+    (($TESTSEC < $AUTOSEC)) && printf PASS || printf FAIL
+    echo " test run took $TESTSEC seconds (expecting ${AUTOSEC} seconds max)"
+    #echo "CODE $TEST_CODE"; exit $TEST_CODE
   else
     echo "PASS test run suceed with exit status 0"
   fi
 
-  if (($AUTO_CODE)); then
+  if (($AUTO_CODE)); then # autotext reported error
     autocode $AUTO_CODE &>/dev/null \
-      && echo "FAIL autotext produced $(autocode $AUTO_CODE) error" \
+      && echo "FAIL autotext exit status was $(autocode $AUTO_CODE)" \
       || echo "FAIL autotext exit status $AUTO_CODE is not known by autocode"
   else
     echo "PASS autotext suceed with exit status 0"
   fi
 
-  # CARE when exit codes differ
   if (($TEST_CODE == $AUTO_CODE)); then
     echo "PASS test run exit status was $TEST_CODE, expected $AUTO_CODE"
   else
-    echo "FAIL autotext returned $AUTO_CODE but exit code is $TEST_CODE"
-    AUTO_CODE=$(autocode EACODE)
+    # CARE must be taken when codes differ, so let's use a case-by-case aproach
+    # TODO THIS SHIT IS FUCKING UGLY AND NO ELEGANT, FUCK OFF AND START AGAIN
+    if (($TEST_CODE==$(autocode OK))) || (($TEST_CODE==$(autocode SIGPIPE)))
+    then
+      case "$(autocode $AUTO_CODE)" in
+        FAIL) echo "FAIL test run '$1' failed" ;;
+        EXCODE) echo "FAIL test run '$1' produced an invalid CODE statement" ;;
+        EATEST) echo "FAIL test run '$1' produced invalid ATP syntax" ;;
+        EATIME) echo "FAIL test run '$1' timed out"; TEST_CODE=0 ;;
+        *) echo "FAIL unexpected autotext exit code $(autocode $AUTO_CODE)" ;;
+      esac
+    elif (($TEST_CODE==$(autocode ENOENT)))&&(($AUTO_CODE==$(autocode EAVOID)))
+    then echo "FAIL file '$1' does not exist"
+    elif (($TEST_CODE==$(autocode EACCES)))&&(($AUTO_CODE==$(autocode EAVOID)))
+    then echo "FAIL user '$USER' can't execute '$1'"
+    elif (($TEST_CODE==$(autocode SIGTERM)))&&(($AUTO_CODE==$(autocode EAOPEN))) \
+      || (($TEST_CODE==$(autocode SIGKILL)))&&(($AUTO_CODE==$(autocode EAOPEN)))
+    then
+      echo "FAIL test run '$1' timed out"
+      verb "force EATIME"; TEST_CODE=$(autocode EATIME)
+    else
+      echo "FAIL code mismatch: $(autocode $TEST_CODE)!=$(autocode $AUTO_CODE)"
+      verb "force EACODE"; TEST_CODE=0 AUTO_CODE=$(autocode EACODE)
+    fi
   fi
 
   # if test execution script failed, that's the code to be reported
   printf "CODE "; (($TEST_CODE)) && echo $TEST_CODE || echo $AUTO_CODE
 
+  verb "will exit now, test_code=$TEST_CODE, auto_code=$AUTO_CODE"
   if (($TEST_CODE != 0)); then exit $TEST_CODE; else exit $AUTO_CODE; fi
   ;;
 esac
