fighting the cowboy: more testing goodness for autotest

diff --git a/example-report b/example-report
--- a/example-report
+++ b/example-report
@@ -13,20 +13,29 @@ autotest report "$EXAMPLE" &>/dev/null \
 echo " report for *unexistant-file* should return error (code > 0)"
 unset EXAMPLE
 
-# The basic failed test (1 pass, 1 skip, 1 fail)
-EXAMPLE="$(autotest root)/example/protocol-v1/fail/basic"
-autotest report "$EXAMPLE" &>/dev/null \
-	&& printf "FAIL" \
-	|| printf "PASS"
-echo " report for $EXAMPLE should return error (code > 0)"
+# generic cases where an error status code should be present 
+# find "$(autotest root)/example/protocol-v1/fail" -type f -print0 \
+#   | while IFS= read -d '' EXAMPLE
+for NAME in {basic,empty,error,error-unit,first}
+do
+  EXAMPLE="$(autotest root)/example/protocol-v1/fail/$NAME"
+  autotest report "$EXAMPLE" &>/dev/null \
+    && printf "FAIL" \
+    || printf "PASS"
+  echo " report for $EXAMPLE should return error (code > 0)"
+done
 unset EXAMPLE
 
-# The empty failed test (no assertions)
-EXAMPLE="$(autotest root)/example/protocol-v1/fail/empty"
-autotest report "$EXAMPLE" &>/dev/null \
-	&& printf "FAIL" \
-	|| printf "PASS"
-echo "  report for $EXAMPLE should return error (code > 0)"
+# cases where a syntax error should be present (exit status code 5)
+find "$(autotest root)/example/protocol-v1/fail" -type f -name 'error*' \
+  -print0 \
+  | while IFS= read -d '' EXAMPLE
+do
+  autotest report "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 5 && printf "PASS" || printf "FAIL"
+  echo " report for $EXAMPLE should exit with code 5 (syntax error)"
+done
 unset EXAMPLE
 
 # TIMEOUT=1 # max seconds to wait until fail
