fighting the cowboy: almost done autotest's unit tests

diff --git a/example b/example
--- a/example
+++ b/example
@@ -32,6 +32,54 @@ done
 unset EXAMPLE
 echo "CODE 0"
 
+echo "TEST $0 v1 examples that should return exit status 1 (assertion error)"
+find-examples /v1/fail -name 'basic*' | while IFS= read -d '' EXAMPLE
+do
+  autotest "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 1 \
+    && echo "PASS $EXAMPLE returns exit status 1 (assertion error)" \
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 1)"
+done
+unset EXAMPLE CODE
+echo "CODE 0"
+
+echo "TEST $0 v1 examples that should return exit status 2 (code mismatch)"
+find-examples /v1/fail -name 'code*' | while IFS= read -d '' EXAMPLE
+do
+  autotest "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 2 \
+    && echo "PASS $EXAMPLE returns exit status 2 (code mismatch)" \
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 2)"
+done
+unset EXAMPLE CODE
+echo "CODE 0"
+
+echo "TEST $0 v1 examples that should return exit status 2 (code mismatch)"
+find-examples /v1/fail -name 'code*' | while IFS= read -d '' EXAMPLE
+do
+  autotest "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 2 \
+    && echo "PASS $EXAMPLE returns exit status 2 (code mismatch)" \
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 2)"
+done
+unset EXAMPLE CODE
+echo "CODE 0"
+
+echo "TEST $0 v1 examples that should return exit status 3 (no assertions)"
+find-examples /v1/fail -name 'empty*' | while IFS= read -d '' EXAMPLE
+do
+  autotest "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 3 \
+    && echo "PASS $EXAMPLE returns exit status 3 (no assertions)" \
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 3)"
+done
+unset EXAMPLE CODE
+echo "CODE 0"
+
 echo "TEST $0 v1 examples that should return exit status 5 (syntax error)"
 find-examples /v1/fail -name 'error*' | while IFS= read -d '' EXAMPLE
 do
@@ -39,9 +87,21 @@ do
   CODE=$?
   test $CODE -eq 5 \
     && echo "PASS $EXAMPLE returns exit status 5 (syntax error)" \
-    || echo "FAIL $EXAMPLE returns exit status $? (expected 5)"
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 5)"
 done
-unset EXAMPLE
+unset EXAMPLE CODE
+echo "CODE 0"
+
+echo "TEST $0 v1 examples that should return exit status 6 (premature keyword)"
+find-examples /v1/fail -name 'premature*' | while IFS= read -d '' EXAMPLE
+do
+  autotest "$EXAMPLE" &>/dev/null
+  CODE=$?
+  test $CODE -eq 6 \
+    && echo "PASS $EXAMPLE returns exit status 6 (premature keyword)" \
+    || echo "FAIL $EXAMPLE returns exit status $CODE (expected 6)"
+done
+unset EXAMPLE CODE
 echo "CODE 0"
 
 echo "TEST $0 v1 examples that should return exit status 0 (success)"
@@ -69,20 +129,7 @@ find-examples /script/pass | while IFS= read -d '' EXAMPLE
 do
   autotest "$EXAMPLE" &>/dev/null \
     && echo "PASS $EXAMPLE returns exit status 0" \
-    || echo "FAIL $EXAMPLE returns exit status $?"
-done
-unset EXAMPLE
-echo "CODE 0"
-
-# scripts that should fail for being too slow (exit status 124)
-#TODO this will timeout the whole test
-echo "TEST $0 script examples being slow that should return 124 (timeout)"
-find-examples /script/fail -name 'slow*' | while IFS= read -d '' EXAMPLE
-do
-  autotest "$EXAMPLE" &>/dev/null
-  test $? -eq 124 \
-    && echo "PASS $EXAMPLE returns exit status 124 (timeout)" \
-    || echo "FAIL $EXAMPLE returns exit status $? (expected 124)"
+    || echo "FAIL $EXAMPLE returns exit status $? (expected 0)"
 done
 unset EXAMPLE
 echo "CODE 0"
diff --git a/example-report b/example-report
--- a/example-report
+++ b/example-report
@@ -1,64 +1,22 @@
 #!/bin/bash
 
-# Emulate a situation where the test executable file does not exist
-EXAMPLE="$(autotest root)/example/protocol-v1/missing"
-test -f "$EXAMPLE" \
-	&& printf "FAIL" \
-	|| printf "PASS"
-echo " example file '$EXAMPLE' should not exist"
+# echo "TEST $0"; echo "SKIP all tests hereafter"; exit 0
 
-autotest report "$EXAMPLE" &>/dev/null \
-	&& printf "FAIL" \
-	|| printf "PASS"
-echo " report for *unexistant-file* should return error (code > 0)"
-unset EXAMPLE
-
-# generic cases where an error status code should be present 
-# find "$(autotest root)/example/protocol-v1/fail" -type f -print0 \
-#   | while IFS= read -d '' EXAMPLE
-for NAME in {basic,empty,error,error-unit,first}
-do
-  EXAMPLE="$(autotest root)/example/protocol-v1/fail/$NAME"
-  autotest report "$EXAMPLE" &>/dev/null \
-    && printf "FAIL" \
-    || printf "PASS"
-  echo " report for $EXAMPLE should return error (code > 0)"
-done
-unset EXAMPLE
-
-# cases where a syntax error should be present (exit status code 5)
-find "$(autotest root)/example/protocol-v1/fail" -type f -name 'error*' \
-  -print0 \
+echo "TEST $0 all example files not being slow"
+find "$(autotest root)/example" -type f -not -name 'slow*' -print0 \
   | while IFS= read -d '' EXAMPLE
 do
+  autotest "$EXAMPLE" &>/dev/null
+  EXPECT=$?
   autotest report "$EXAMPLE" &>/dev/null
-  CODE=$?
-  test $CODE -eq 5 && printf "PASS" || printf "FAIL"
-  echo " report for $EXAMPLE should exit with code 5 (syntax error)"
+  ACTUAL=$?
+  test $ACTUAL -eq $EXPECT \
+    && echo "PASS $EXAMPLE returns exit status $EXPECT" \
+    || echo "FAIL $EXAMPLE returns exit status $ACTUAL (expected $EXPECT)"
 done
-unset EXAMPLE
+unset EXAMPLE EXPECT ACTUAL
 
-# TIMEOUT=1 # max seconds to wait until fail
-# find "$autodir/example" -type f -print0 \
-# 	| while IFS= read -d '' filepath
-# do
-# 	#echo  "go for '$filepath'"; exit
-# 	(timeout $TIMEOUT autotest "$filepath") >/dev/null
-# 	code=$?
-# 	test $code -ne 124
-# 	tested "'autotest $filepath' runs in less than $TIMEOUT seconds"
-# 	test $code -eq 0
-# 	tested "running 'autotest $filepath' returns 0"
-# 	unset code
-# 
-# 	timeout $TIMEOUT autotest report "$filepath" >/dev/null
-# 	code=$?
-# 	test $code -ne 124
-# 	tested "'autotest report $filepath' runs in less than $TIMEOUT seconds"
-# 	test $code -eq 0
-# 	tested "'autotest report $filepath' returns 0"
-# 	unset code
-# done
+# TODO slow tests
 
 ##
 # vim modeline
