removed run-tests script. Now 'iai test' is the way to run the full test suite

diff --git a/test/bash/all b/test/bash/all
--- a/test/bash/all
+++ b/test/bash/all
@@ -3,32 +3,78 @@
 # Can't use `-e`, or it's not possible to "catch" errors after they fire up
 set +e
 
-# TODO iterating over an array of filenames is a "bash-bad-practice"
-#      (it is done over an over here)
-
 ##
-# tested tool is the first thing to check for
-source "bash/tested.bash" && tested--test || {
-  echo "CANT START TESTS"
-  exit 1
+# testing toolset is the first thing to check for
+# TODO testodo <<<"tool to report tests pending to write"
+testools=(tested teskip)
+
+for tool in ${testools[@]}; do source "bash/$tool.bash"; done
+
+report="$( for tool in ${testools[@]}; do ${tool}--test || exit; done )" || {
+  echo "###################################"
+  echo "- - - check bash errors above - - -"
+  echo "             = = = = =             "
+  echo "     TEST TOOLS CHECKUP FAILED     "
+  echo "             = = = = =             "
+	echo "- - - check test report below - - -"
+  echo "###################################"
+	echo "$report"
+  echo "###################################"
+  echo "Sorry, can't run test suite because 'testools' checkup failed"
+	exit 1
 }
 
-##
-# bash lib tests are the next thing to check. iai needs that lib to work
-# TODO WTF are abc.bash tests? stop cowboy coding PLEASE!
-# TODO WTF are abc-call_trace.bash tests? stop cowboy coding PLEASE!
-# TODO Seems ideal to list bash/*.bash and check every lib file has a test file
+# TODO Could be better checking for test filenames based on code filenames?
+# TODO for example, list bash/*.bash and check every lib file has tests
+# TODO it would ease pending test identify
 #test $(find test/bash -name "bashlib-*" | wc -l) -gt 0
 #tested "there are at least 1 bash test"
 #find test/bash -name "bashlib-*" -exec './{}' \;
-bashlibtests=("$(ls test/bash/bashlib-*)") || oops "list bashlib tests!"
-test "${#bashlibtests[@]}" -eq "0" && oops "found no bashlib tests!"
-for file in ${bashlibtests[@]}; do
-	echo "Running test $(basename "$file")... "
-  # run test scripts within a subshell to avoid polluting env
-  ("./$file") &>/dev/null # hide both output streams
-	tested "bashlib test '$file'"
-done
+
+run_tests_for () {
+	local prefix="${1:?"$FUNCNAME: argument must be specified (prefix)"}"
+
+	# TODO iterating over an array of filenames is a "bash-bad-practice"
+	# TODO i should use `find` with `-exec` action instead
+  testfiles=("$(ls test/bash/${prefix}-*)")
+
+	test "${#testfiles[@]}" -gt "0" ;tested "There is at least 1 $prefix test"
+
+	for file in ${testfiles[@]}; do
+		# TODO content convention tests
+		# ex: `grep "[ ;]tested[ ]" test/bash/bashlib-assert-code`
+		#   to seek tested calls and check the code style for them
+		# TODO generate stats to calculate progress ¿or even introspection?
+		# ex: `grep -c "[ ;]tested[ ]" test/bash/bashlib-assert-code`
+		#   to count the minimum expected times that `tested` should be called
+
+		echo -en "> Running test '$(basename "$file")'...\n  " # pad reports
+		("./$file") &>/dev/null # hide both output streams
+		tested "running $file in a subshell returns 0" # test $? -eq 0 implicit
+		# running in a subshell avoids env pollution and unexpected exits
+
+		# TODO measure the time spent by each test
+		# TODO dot animation while running?
+		# TODO progress could be `echo .` for each tested call?
+		# TODO both outs were hidden because working with a test fail implies isolating
+		# TODO interactively allow developer at this tty (if it's a tty) to do so?
+		# TODO maybe save report=$(./$file) and print it if failed?
+	done
+	tested "All '$prefix' test scripts pass running in a subshell"
+}
+
+##
+# bash lib tests are the next thing to check. iai cmds depend on it
+# TODO WTF are abc.bash tests? stop cowboy coding PLEASE!
+# TODO WTF are abc-call_trace.bash tests? stop cowboy coding PLEASE!
+# TODO rename bashlib to bashido
+run_tests_for "bashlib"
+
+##
+# next procede with iai cmd tests, iai interactive cli depends on it
+run_tests_for "iaicmd"
+
+# TODO iai interactive commands (expecting developer interaction)
 
 cat <<TODOS >&2
 TODOs at file '${BASH_SOURCE[0]}':
@@ -37,8 +83,7 @@ TODOs at file '${BASH_SOURCE[0]}':
   - seems easy to implement but
   WRITE TESTS FIRST with diff_test
   - stop fucking cowboy coding
-#3 tool to signal "workinghere"
-  - use caller to get filename
+  - use caller to get filename and signal a "workinghere" msg
   ##
   # Extra tests for better _developer experience_
   # TODO test that utilities ease debugging
@@ -46,23 +91,22 @@ TODOs at file '${BASH_SOURCE[0]}':
   # - 'tested' utility outputs call trace
   # TODO test that utilities ease developing
   # - each source file ends with vim modeline
+#4 Integrate a code coverage tool, i.e. https://simonkagstrom.github.io/kcov/
 TODOS
 
 echo -e "#################\n KEEP WORKING ON \n#################"
-exit 1
 
-##
-# next procede with iai command line tools tests
-iaicmdtests=("$(ls test/bash/iaicmd-*)") || cant "list iaicmd tests!"
-test "${#iaicmdtests[@]}" -eq "0" && cant "find any iaicmd tests!"
-for file in ${iaicmdtests[@]}; do
-  "./$file"; tested "iaicmd test '$file'"
-done
 
-echo "######################"
-echo "! All tests were run !"
-echo "######################"
-echo "              good job :D"
+cat <<DONE
+######################
+! All tests were run !
+######################
+              good job :D
+
+Now continue with TDD and write more test scripts.
+Don't enter cowboy coding mode please!
+DONE
+
 ##
 # vim modeline
 # /* vim: set filetype=sh ts=2 shiftwidth=2: */
