worked hard at shitbook

diff --git a/test/bash/all b/test/bash/all
--- a/test/bash/all
+++ b/test/bash/all
@@ -8,9 +8,9 @@ set +e
 # TODO testodo <<<"tool to report tests pending to write"
 testools=(tested teskip)
 
-for tool in ${testools[@]}; do source "bash/$tool.bash"; done
+for tool in ${testools[@]}; do source "bash/autotest-$tool.bash"; done
 
-report="$( for tool in ${testools[@]}; do ${tool}--test || exit; done )" || {
+report="$( for tool in ${testools[@]}; do ${tool}--test "$tool" || exit; done )" || {
   echo "###################################"
   echo "- - - check bash errors above - - -"
   echo "             = = = = =             "
@@ -24,13 +24,33 @@ report="$( for tool in ${testools[@]}; do ${tool}--test || exit; done )" || {
 	exit 1
 }
 
+####
+# Capturing any command's stderr and stdout separately
+# TODO should this be at autotest-testrun.bash ?
+#
+## Reference
+# Basis found at http://stackoverflow.com/q/11027679/1894803
+# the working (and ugly) aproach is using `eval` and `typeset -p` (`declare`)
+# it's well explained at http://stackoverflow.com/a/26827443/1894803
+# but as seen at http://stackoverflow.com/a/28796214/1894803
+# it can be refactored ussing a helper function and `printf -v`
+#
+## Example
+# eval "$(declare_results 'commandline with argument list')"
+# echo "stdout is: |$stdout| stderr is: |$stderr| return code is: |$exited|"
+declare_stdin_as () { printf -v "$1" "%s" "$(cat)"; typeset -p "$1"; }
+declare_results () {
+	local cmd="$@"
+	("$cmd") 2> >(declare_stdin_as stderr) 1> >(declare_stdin_as stdout)
+	declare_stdin_as exited <<<"$?"
+}
+
 # TODO Could be better checking for test filenames based on code filenames?
 # TODO for example, list bash/*.bash and check every lib file has tests
 # TODO it would ease pending test identify
 #test $(find test/bash -name "bashlib-*" | wc -l) -gt 0
 #tested "there are at least 1 bash test"
 #find test/bash -name "bashlib-*" -exec './{}' \;
-
 run_tests_for () {
 	local prefix="${1:?"$FUNCNAME: argument must be specified (prefix)"}"
 
@@ -48,11 +68,23 @@ run_tests_for () {
 		# ex: `grep -c "[ ;]tested[ ]" test/bash/bashlib-assert-code`
 		#   to count the minimum expected times that `tested` should be called
 
-		echo -en "> Running test '$(basename "$file")'...\n  " # pad reports
+		local basename="$(basename "$file")"
+		echo "> Running test file '$file'..." # pad reports
 		SECONDS=0 # Crude time calc from http://stackoverflow.com/a/8903280/1894803
-		("./$file") &>/dev/null # hide both output streams
-		tested "running $file in a subshell returns 0 (${SECONDS}s)"
-		# running in a subshell avoids env pollution and unexpected exits
+		eval "$(declare_results "./$file")"
+		(( exited )) && {
+		  echo "  ./$file exited with code $exited"
+			if test -n "$stdout"; then
+				echo "  - - stdout - -"; echo "$stdout"; echo "  - - * ** * - -"
+			fi
+			if test -n "$stderr"; then
+				echo "  - - stderr - -"; echo "$stderr"; echo "  - - * ** * - -"
+			fi
+	  }
+		test $exited -eq 0
+		tested "running $basename in a subshell returns 0 (${SECONDS}s)"
+		# exec file in a subshell avoids env pollution and unexpected exits
+		# declare_results actually execs command line within a subshell
 
 		# TODO measure the time spent by each test better, consider `time`
 		# TODO dot animation while running?
diff --git a/test/bash/bashlib-assert-outputs b/test/bash/bashlib-assert-outputs
--- a/test/bash/bashlib-assert-outputs
+++ b/test/bash/bashlib-assert-outputs
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-source bash/tested.bash || exit
+source bash/autotest.bash || exit
 source bash/assert.bash || exit
 source bash/basic-str.bash || exit
 
@@ -92,7 +92,6 @@ test $(wc -l <<<"$out") -eq 1
 tested "diff_test outputs 1 lines total when there are 1 line that differs"
 (
 	function print_details(){
-
 		echo "- - - DISPLAY - - -"; echo "$out"
 		echo "- - - CONTENT - - -"; printf "%q\n" "$out"
 		false # designed to provide details after a known failure
@@ -117,6 +116,74 @@ tested "diff_test outputs 1 lines total when there are 1 line that differs"
 )
 tested "diff_test emphatizes the non-expected output of a line"
 
+out="$(diff_test <(cat <<ACTUAL
+*******************************
+###############################
+#OOPS! MULTI-LINE IS NOT EMPTY#
+###############################
+*******************************
+ACTUAL
+) <(echo) )"
+(
+	test $? -eq 1
+	tested 'diff_test reports differences when line lengths differ'
+	
+	print_details () {
+		echo "- - - DISPLAY - - -"; echo "$out"
+	  echo "- - - FILTERD - - -"; echo "$(str_ansifilter "$out")"
+		echo "- - - CONTENT - - -"; printf "%q\n" "$out"
+		false # designed to provide details after a known failure
+	}
+
+	test $(wc -l <<<"$out") -eq 5 || print_details
+	tested "diff_test outputs 5 lines total when there are 5 lines that differs"
+	n=0; while IFS= read line; do
+		case "$((++n))" in
+			1|5) thing="*******************************" ;;
+			2|4) thing="###############################" ;;
+			3)   thing="#OOPS! MULTI-LINE IS NOT EMPTY#" ;;
+			*) echo "expected 5 lines at most"; exit 1 ;;
+		esac
+		[[ "$(str_ansifilter "$line")" =~ '^'"$thing"'|'{1,2}'$' ]] || print_details
+		tested "line $n contains expected visible output"
+	done <<<"$out"
+)
+tested "diff_test works even when source1 has more lines than source2"
+
+out="$(diff_test <(echo) <(cat <<EXPECT
+*******************************
+###############################
+#OOPS! MULTI-LINE IS NOT EMPTY#
+###############################
+*******************************
+EXPECT
+))"
+(
+	test $? -eq 1
+	tested 'diff_test reports differences when line lengths differ'
+	
+	print_details () {
+		echo "- - - DISPLAY - - -"; echo "$out"
+	  echo "- - - FILTERD - - -"; echo "$(str_ansifilter "$out")"
+		echo "- - - CONTENT - - -"; printf "%q\n" "$out"
+		false # designed to provide details after a known failure
+	}
+
+	test $(wc -l <<<"$out") -eq 5 || print_details
+	tested "diff_test outputs 5 lines total when there are 5 lines that differs"
+	n=0; while IFS= read line; do
+		case "$((++n))" in
+			1|5) thing="*******************************" ;;
+			2|4) thing="###############################" ;;
+			3)   thing="#OOPS! MULTI-LINE IS NOT EMPTY#" ;;
+			*) echo "expected 5 lines at most"; exit 1 ;;
+		esac
+		[[ "$(str_ansifilter "$line")" =~ '^''|'{1,2}"$thing"'$' ]] || print_details
+		tested "line $n contains expected visible output"
+	done <<<"$out"
+)
+tested "diff_test works even when source1 has less lines than source2"
+
 out="$(diff_test <( echo -e "1-\n2-\n3-" ) <<EXPECT
 1-
 2-
@@ -139,6 +206,58 @@ out="$( diff_test <( echo "some text" ) <<<"some text" )"
 	tested  "outputs nothing to stdout when both sources are equal"
 )
 tested  "'diff_test' accepts input from a process substitution and a herestring"
+
+print_details () {
+	echo "code was $code"
+	echo "- - - DISPLAY - - -"; echo "$out"
+	echo "- - - CONTENT - - -"; printf "%q\n" "$out"
+	false # designed to provide details after a known failure
+}
+
+unset out code empty; empty=""
+out=$( diff_test <( echo ) <<<"$empty" ); code=$?
+test $code -eq 0 || print_details
+tested "returns 0 when actual is newline and stdin is empty"
+test -z "$out" || print_details
+tested "outputs nothing when actual is newline and stdin is empty"
+
+unset out code
+out=$( diff_test <( echo "some text" ) <<<"$empty" ); code=$?
+test $code -eq 1 || print_details
+tested "returns 1 when actual value is 'some text' and stdin is empty"
+test -n "$out" || print_details
+tested "outputs something when actual is 'some text' and stdin is empty"
+
+unset out code
+out=$( diff_test <(echo "$empty") <<<"some text" ); code=$?
+test $code -eq 1 || print_details
+tested "returns 1 when actual is empty and stdin is 'some text'"
+test -n "$out" || print_details
+tested "outputs something when actual is empty and stdin is 'some text'"
+
+unset out code
+out=$( diff_test <( eval "echo something" ) <<<"$empty" ); code=$?
+test $code -eq 1 || print_details
+tested "returns 1 when actual is 'something' and stdin is empty"
+test -n "$out" || print_details
+tested "outputs something when actual is empty and stdin is 'some text'"
+
+unset out code
+out=$( diff_test <( eval "echo" ) <<<"$empty" ); code=$?
+test $code -eq 0 || print_details
+tested "returns 0 when actual is output of 'eval echo' and stdin is empty"
+test -z "$out" || print_details
+tested "outputs nothing when actual is empty and stdin is empty"
+
+unset out code
+# observe that `cat /dev/null` != `cat <<<""`
+out=$( diff_test /dev/null <<<"$empty" ); code=$?
+test $code -eq 1 || print_details
+tested "returns 1 when actual is /dev/null and stdin is empty"
+test -n "$out" || print_details
+tested "outputs something when actual is /dev/null and stdin is empty"
+[[ "$(str_ansifilter "$out")" =~ '^''|'{1,2}'\n$' ]] || print_details
+tested "output has \n as expected when actual is /dev/null and stdin is empty"
 
 ##
 # vim modeline
