refactoring the test runner: Autotest Protocol v1

diff --git a/abc/command/iai-test b/abc/command/iai-test
--- a/abc/command/iai-test
+++ b/abc/command/iai-test
@@ -1,54 +1,83 @@
 assert_function iai || exit
 
 function iai-test () {
-  test $# -gt 0 && fail "expecting no arguments"
-  find "$(iai path test/abc)" -type f -print0 \
-    | while IFS= read -d '' file; do
-      # running the file within a subshell allows catching allways a code
-      echo "TEST $file"; (exec "$file") 2>/dev/null; echo "CODE $?"
-    done \
-    | iai-test.report-dots 
+  local reporter="iai-test.report" report="dot-code"
+  local fullpath="$(iai path test/abc)" action="allin"
+
+  while test $# -gt 0
+  do
+    if is_function "$reporter-$1"; then report=$1
+    elif test "$1" == "bail"; then report="fails"; action="bail"
+    elif test -d "$1"; then fullpath="$(realpath $1)"
+    elif test -f "$1"; then fullpath="$(realpath $1)"; action="alone"
+    else fail "unexpected argument (%s)" "$1"; fi
+    shift # remove the parsed argument
+  done
+  assert_function "iai-test.$action"; assert_function "$reporter-$report"
+  "iai-test.$action" "$fullpath" | "$reporter-$report"
 }
 
-# TODO this validation pass-through stream belongs to autotest
-function iai-test.itp-stream () {
-  local tlvl=0 clvl=0 fifo='passtrought' return=0
-  while read keyword value; do
-    case $keyword in
-      TEST)
-        if ! test -f "$value"; then
-          emsg "EATEST: %s is not a file" "$value"; return=3; break
-        fi
-        if test $tlvl -eq $clvl; then let tlvl++; else
-          emsg "EATEST: expecting CODE before %s" TEST; return=4; break
-        fi
-        ;;
-      PASS|FAIL|SKIP) : ;;
-      CODE)
-        if ! is_int "$value" && test $value -lt 256; then
-          emsg "EATEST: invalid code (%s)" "$value"; return=3; break
-        fi
-        if test $clvl -lt $tlvl; then let clvl++; else
-          emsg "EATEST: expecting TEST before %s" CODE; return=4; break
-        fi
-        ;;
-      *) emsg "EATEST: bad syntax: %s" "$keyword $value"; return=2; break ;;
-    esac
-    echo "$keyword $value" # pass data down through pipeline
-  done
-  test $return -gt 0 && return $return
-  test $tlvl -gt 0 || emsg "EATEST: expecting at least one TEST" && return 5
-  test $tlvl -eq $clvl || fail "EATEST: expecting final CODE" && return 6
+function iai-test.allin () {
+  test $# -eq 1 || fail "expecting one argument"
+  test -d "$1" || fail "'$1' is not a directory"
+  find "$1" -type f -executable -exec autotest report '{}' \;
+}
+
+# TODO DRY please
+function iai-test.bail () {
+  test $# -eq 1 || fail "expecting one argument"
+  test -d "$1" || fail "'$1' is not a directory"
+  find "$1" -type f -executable \( -exec autotest report '{}' \; -o -quit \)
+}
+
+function iai-test.alone () {
+  test $# -eq 1 || fail "expecting one argument"
+  test -f "$1" || fail "%s is not a file" "$1"
+  autotest report "$1"
 }
 
 function iai-test.report-dots () {
-  iai-test.itp-stream | while read keyword value; do
+  while read keyword value; do
     case $keyword in
-      TEST) printf "%s " "${value#$PWD/}" ;;
+      TEST) printf "[" ;;
       PASS) printf "·" ;;
       FAIL) printf "X" ;;
       SKIP) printf "-" ;;
-      CODE) (( $value )) && echo "X CODE $value" || echo "· OK";;
+      CODE) printf "]%s" "$value";;
+    esac
+  done; printf '\n'
+}
+
+function iai-test.report-dot-code () {
+  while read keyword value; do
+    case $keyword in
+      TEST) printf "%s\t[" "${value#$PWD/}" ;;
+      PASS) printf "·" ;;
+      FAIL) printf "X" ;;
+      SKIP) printf "-" ;;
+      CODE) printf "]\t"; (( $value )) && echo "CODE $value" || echo "OK" ;;
+    esac
+  done
+}
+
+# TODO this is so ugly on screen
+function iai-test.report-fails () {
+  local fails=0
+  while read keyword value; do
+    case $keyword in
+      TEST) printf "> %s ...\n" "${value#$PWD/}" ;;
+      PASS|SKIP) : ;;
+      FAIL) printf "|> %s\n" "$value"; let fails++ ;;
+      CODE)
+        if (($value)) || (($fails)); then
+          local expected="0"
+          (($fails)) && expected="not 0"
+          printf "|> status code was %s while expecting %s\n" $value "$expected"
+          printf "|> CODE $value (%s fails)\n" "$fails"
+          break # bail on first test that fails
+        else
+          echo "OK"
+        fi
     esac
   done
 }
