better logging for iai-sync

diff --git a/abc/command/iai-sync b/abc/command/iai-sync
--- a/abc/command/iai-sync
+++ b/abc/command/iai-sync
@@ -16,19 +16,17 @@ function iai-sync-repo () {
   cd "$repo" || fail
   repo="~${repo#$HOME}"
   info "going to sync git repo at $repo"
-  verb "- - - pulling... - - -"
-  git pull |& verb
-  test ${PIPESTATUS[-2]} -gt 0 && fail "can't pull"
-  verb "- - - pushing... - - -"
-  git push |& verb
-  test ${PIPESTATUS[-2]} -gt 0 && fail "can't push"
+  utip "> git pull"
+  git pull || fail "can't pull"
+  utip "> git push"
+  git push || fail "can't push"
   if test "$(hostname)" != "shitbook"
   then
-    verb "- - - pulling on shitbook... - - -"
+    utip "> remote pull @shitbook"
     ssh shitbook "cd $repo && git pull" |& verb
     test ${PIPESTATUS[-2]} -gt 0 && fail "can't pull on shitbook"
   fi
-  utip "git status # (local) after sync!"
+  utip "> git status # (local) after sync!"
   git status
 }
 
@@ -37,7 +35,7 @@ function iai-sync-all () {
 	{
 		iai-sync-repo ~/Proxectos/iai
     iai-sync-repo ~/Proxectos/empresa.lorenzogrv.com
-	} |& utip
+	} # |& utip
   info "Sincronizados todos os repositorios."
 }
 
