add iai-ssh-auth as builtin (this should not be a builtin)

diff --git a/script/iai b/script/iai
--- a/script/iai
+++ b/script/iai
@@ -159,6 +159,28 @@ function iai-lanip () {
 	ip route get 8.8.8.8 | awk '{print $7; exit}' || exit 1;
 }
 
+function iai-ssh-auth {
+	iai.dependencies || exit
+	which scp &>/dev/null || fail "scp not found"
+
+	local host="$1"
+	test -z "$host" && fail "Missing argument 1: hostname to be authorized"
+
+	info "Getting the id_rsa.pub file from '%s'" "$host"
+	test -e id_rsa.pub && fail "id_rsa.pub already exists at pwd"
+	scp "$host:~/.ssh/id_rsa.pub" . || fail "something went wrong"
+
+	local idfile="~/.ssh/${host}--id_rsa.pub"
+	verb "Moving the key file to %s" "$idfile"
+	mv id_rsa.pub "$idfile" || fail "something went wrong"
+
+	verb "Adding the key to '.ssh/authorized_keys'"
+	cat "$idfile" >> "~/.ssh/authorized_keys" || fail "something went wrong"
+
+	info "Successfully added $host's key" "$host"
+	utip "Now you can ssh into this system from %s" "$host"
+}
+
 ##
 # `iai root` outputs the directory where iai resides (the "iai root").
 # It's probably the most basic operation besides the "artistic" bare `iai`,
