found some old work without being comited (hopes). (Ouch!)

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,7 +1,23 @@
 #!/usr/bin/env bash
 
-for file in $(find test/*.js)
-do
-  echo "> iai-test --once --mute $file"
-  ./bin/iai-test --once --mute $file && echo "- OK" || exit 1
-done
+#for file in $(find test/*.js)
+#do
+#  echo "> iai-test --once --mute $file"
+#  ./bin/iai-test --once --mute $file && echo "- OK" || exit 1
+#done
+
+test_mod(){
+  MPATH=$1
+  MNAME=${MPATH/.\//iai-}
+  MNAME=${MNAME//\//-}
+  echo "going to test $MNAME ($MPATH)"
+  CURR=$(pwd)
+  cd $MPATH && npm test && cd $CURR || (echo "$MNAME tests failed" && exit 1)
+}
+
+test_mod "./abc"
+test_mod "./api/view"
+test_mod "./api/server"
+#cd ./api/view && npm test && cd .. || echo "iai-api-view tests do not pass" && exit 1
+#cd ./api/server && npm test && cd .. || echo "iai-api-server tests do not pass" && exit 1
+
